// Code generated by irpc generator; DO NOT EDIT
// Source: irpc_tcp_example/backend.go
package irpc_tcp_example

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
	"time"
)

var _BackendIrpcId = []byte{
	0x97, 0x60, 0xb5, 0x5a, 0x15, 0xbf, 0x3b, 0x64,
	0xab, 0x2f, 0xb2, 0x8c, 0x2b, 0x89, 0xa8, 0x81,
	0x08, 0xaa, 0xe0, 0xcf, 0xd4, 0x3b, 0x4f, 0x71,
	0x83, 0x8c, 0xf5, 0xf3, 0x77, 0x99, 0xbf, 0x59,
}

// BackendIrpcService provides [Backend] interface over irpc
type BackendIrpcService struct {
	impl Backend
}

// NewBackendIrpcService returns new [irpcgen.Service] forwarding [Backend] network calls to impl
func NewBackendIrpcService(impl Backend) *BackendIrpcService {
	return &BackendIrpcService{
		impl: impl,
	}
}

// Id implements [irpcgen.Service] interface.
func (s *BackendIrpcService) Id() []byte {
	return _BackendIrpcId
}

// GetFuncCall implements [irpcgen.Service] interface
func (s *BackendIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // ReverseString
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_Backend_ReverseStringReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_Backend_ReverseStringResp
				resp.p0, resp.p1 = s.impl.ReverseString(args.in)
				return resp
			}, nil
		}, nil
	case 1: // RepeatString
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_Backend_RepeatStringReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_Backend_RepeatStringResp
				resp.p0, resp.p1 = s.impl.RepeatString(args.in, args.n)
				return resp
			}, nil
		}, nil
	case 2: // TimeToString
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_Backend_TimeToStringReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_Backend_TimeToStringResp
				resp.p0, resp.p1 = s.impl.TimeToString(args.t)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// BackendIrpcClient implements [Backend] interface. It by forwards calls over network to [BackendIrpcService] that provides the implementation.
//
// Backend interface defines functions, that will be avalable to be called over the network
// we return error from every function, because network errors can occur even for functions, that cannot error otherwise
// string utils obviously make no sense to be called remotely, but it's just an example
type BackendIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func NewBackendIrpcClient(endpoint irpcgen.Endpoint) (*BackendIrpcClient, error) {
	if err := endpoint.RegisterClient(_BackendIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &BackendIrpcClient{endpoint: endpoint}, nil
}

// ReverseString implements [Backend]
//
func (_c *BackendIrpcClient) ReverseString(in string) (string, error) {
	var req = _irpc_Backend_ReverseStringReq{
		in: in,
	}
	var resp _irpc_Backend_ReverseStringResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _BackendIrpcId, 0, req, &resp); err != nil {
		var zero _irpc_Backend_ReverseStringResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}

// RepeatString implements [Backend]
func (_c *BackendIrpcClient) RepeatString(in string, n int) (string, error) {
	var req = _irpc_Backend_RepeatStringReq{
		in: in,
		n:  n,
	}
	var resp _irpc_Backend_RepeatStringResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _BackendIrpcId, 1, req, &resp); err != nil {
		var zero _irpc_Backend_RepeatStringResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}

// TimeToString implements [Backend]
func (_c *BackendIrpcClient) TimeToString(t time.Time) (string, error) {
	var req = _irpc_Backend_TimeToStringReq{
		t: t,
	}
	var resp _irpc_Backend_TimeToStringResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _BackendIrpcId, 2, req, &resp); err != nil {
		var zero _irpc_Backend_TimeToStringResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}

type _irpc_Backend_ReverseStringReq struct {
	in string
}

func (s _irpc_Backend_ReverseStringReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.in); err != nil {
		return fmt.Errorf("serialize \"in\" of type string: %w", err)
	}
	return nil
}
func (s *_irpc_Backend_ReverseStringReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.in); err != nil {
		return fmt.Errorf("deserialize in of type string: %w", err)
	}
	return nil
}

type _irpc_Backend_ReverseStringResp struct {
	p0 string
	p1 error
}

func (s _irpc_Backend_ReverseStringResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.p0); err != nil {
		return fmt.Errorf("serialize type string: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_Backend_ReverseStringResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type string: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_Backend_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _error_Backend_impl struct {
	_Error_0_ string
}

func (i _error_Backend_impl) Error() string {
	return i._Error_0_
}

type _irpc_Backend_RepeatStringReq struct {
	in string
	n  int
}

func (s _irpc_Backend_RepeatStringReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.in); err != nil {
		return fmt.Errorf("serialize \"in\" of type string: %w", err)
	}
	if err := irpcgen.EncInt(e, s.n); err != nil {
		return fmt.Errorf("serialize \"n\" of type int: %w", err)
	}
	return nil
}
func (s *_irpc_Backend_RepeatStringReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.in); err != nil {
		return fmt.Errorf("deserialize in of type string: %w", err)
	}
	if err := irpcgen.DecInt(d, &s.n); err != nil {
		return fmt.Errorf("deserialize n of type int: %w", err)
	}
	return nil
}

type _irpc_Backend_RepeatStringResp struct {
	p0 string
	p1 error
}

func (s _irpc_Backend_RepeatStringResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.p0); err != nil {
		return fmt.Errorf("serialize type string: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_Backend_RepeatStringResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type string: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_Backend_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _irpc_Backend_TimeToStringReq struct {
	t time.Time
}

func (s _irpc_Backend_TimeToStringReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBinaryMarshaler(e, s.t); err != nil {
		return fmt.Errorf("serialize \"t\" of type time.Time: %w", err)
	}
	return nil
}
func (s *_irpc_Backend_TimeToStringReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBinaryUnmarshaler(d, &s.t); err != nil {
		return fmt.Errorf("deserialize t of type time.Time: %w", err)
	}
	return nil
}

type _irpc_Backend_TimeToStringResp struct {
	p0 string
	p1 error
}

func (s _irpc_Backend_TimeToStringResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.p0); err != nil {
		return fmt.Errorf("serialize type string: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_Backend_TimeToStringResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type string: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_Backend_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}
