// Code generated by irpc generator; DO NOT EDIT
package irpc_tcp_example

import (
	"context"
	"fmt"
	"github.com/marben/irpc/pkg/irpc"
)

type RemoteMathIRpcService struct {
	impl RemoteMath
	id   []byte
}

func NewRemoteMathIRpcService(impl RemoteMath) *RemoteMathIRpcService {
	return &RemoteMathIRpcService{
		impl: impl,
		id:   []byte{220, 185, 216, 81},
	}
}
func (s *RemoteMathIRpcService) Id() []byte {
	return s.id
}
func (s *RemoteMathIRpcService) GetFuncCall(funcId irpc.FuncId) (irpc.ArgDeserializer, error) {
	switch funcId {
	case 0: // Add
		return func(d *irpc.Decoder) (irpc.FuncExecutor, error) {
			// DESERIALIZE
			var args _Irpc_RemoteMathAddReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpc.Serializable {
				// EXECUTE
				var resp _Irpc_RemoteMathAddResp
				resp.Param0_, resp.Param1_ = s.impl.Add(args.Param0_a, args.Param1_b)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

type RemoteMathIRpcClient struct {
	endpoint *irpc.Endpoint
	id       []byte
}

func NewRemoteMathIRpcClient(endpoint *irpc.Endpoint) (*RemoteMathIRpcClient, error) {
	id := []byte{220, 185, 216, 81}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &RemoteMathIRpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *RemoteMathIRpcClient) Add(a int, b int) (int, error) {
	var req = _Irpc_RemoteMathAddReq{
		Param0_a: a,
		Param1_b: b,
	}
	var resp _Irpc_RemoteMathAddResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &resp); err != nil {
		var zero _Irpc_RemoteMathAddResp
		return zero.Param0_, err
	}
	return resp.Param0_, resp.Param1_
}

type _Irpc_RemoteMathAddReq struct {
	Param0_a int
	Param1_b int
}

func (s _Irpc_RemoteMathAddReq) Serialize(e *irpc.Encoder) error {
	if err := e.VarInt(s.Param0_a); err != nil {
		return fmt.Errorf("serialize s.Param0_a of type 'int': %w", err)
	}
	if err := e.VarInt(s.Param1_b); err != nil {
		return fmt.Errorf("serialize s.Param1_b of type 'int': %w", err)
	}
	return nil
}
func (s *_Irpc_RemoteMathAddReq) Deserialize(d *irpc.Decoder) error {
	if err := d.VarInt(&s.Param0_a); err != nil {
		return fmt.Errorf("deserialize s.Param0_a of type 'int': %w", err)
	}
	if err := d.VarInt(&s.Param1_b); err != nil {
		return fmt.Errorf("deserialize s.Param1_b of type 'int': %w", err)
	}
	return nil
}

type _Irpc_RemoteMathAddResp struct {
	Param0_ int
	Param1_ error
}

func (s _Irpc_RemoteMathAddResp) Serialize(e *irpc.Encoder) error {
	if err := e.VarInt(s.Param0_); err != nil {
		return fmt.Errorf("serialize s.Param0_ of type 'int': %w", err)
	}
	{
		var isNil bool
		if s.Param1_ == nil {
			isNil = true
		}
		if err := e.Bool(isNil); err != nil {
			return fmt.Errorf("serialize isNil of type 'bool': %w", err)
		}

		if !isNil {
			{ // Error()
				_Error_0_ := s.Param1_.Error()
				if err := e.String(_Error_0_); err != nil {
					return fmt.Errorf("serialize _Error_0_ of type 'string': %w", err)
				}
			}
		}
	}
	return nil
}
func (s *_Irpc_RemoteMathAddResp) Deserialize(d *irpc.Decoder) error {
	if err := d.VarInt(&s.Param0_); err != nil {
		return fmt.Errorf("deserialize s.Param0_ of type 'int': %w", err)
	}
	{
		var isNil bool
		if err := d.Bool(&isNil); err != nil {
			return fmt.Errorf("deserialize isNil of type 'bool': %w", err)
		}

		if isNil {
			s.Param1_ = nil
		} else {
			var impl _error_RemoteMath_irpcInterfaceImpl
			{ // Error()
				if err := d.String(&impl._Error_0_); err != nil {
					return fmt.Errorf("deserialize impl._Error_0_ of type 'string': %w", err)
				}
			}
			s.Param1_ = impl
		}
	}
	return nil
}

type _error_RemoteMath_irpcInterfaceImpl struct {
	_Error_0_ string
}

func (i _error_RemoteMath_irpcInterfaceImpl) Error() string {
	return i._Error_0_
}
